name: Deploy Plant Shopping App

on:
  push:
    branches: [ main ]
    paths:
      - 'Final Project/e-plantShopping/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd "Final Project/e-plantShopping"
          npm install

      - name: Build
        run: |
          cd "Final Project/e-plantShopping"
          npm run build
        env:
          CI: false

      - name: Create output directory
        run: |
          mkdir -p build_output
          cp -R "Final Project/e-plantShopping/dist/"* build_output/
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build_output
          clean: true
          target-folder: "e-plantShopping"