name: Deploy e-plantShopping to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'Final Project/e-plantShopping/**'
      - '.github/workflows/deploy-e-plantshopping.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'Final Project/e-plantShopping'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'Final Project/e-plantShopping/package-lock.json'

      - run: npm ci
      - run: npm run build

      # Nếu Vite: output = dist ; nếu CRA: đổi thành build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'Final Project/e-plantShopping/dist'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
